export const API_PATHS = {
  LOGIN: '/login',
  LOGOUT: '/logout',
  INVOICE_LIST: '/invoice/list',
  INVOICE_FETCH_ONE: '/invoice',
  INVOICE_CREATE: '/invoice/create',
  INVOICE_EDIT: '/invoice/edit',
  INVOICE_DELETE: '/invoice/delete',
  INVOICE_EXPORT_EXCEL: '/invoice/export-excel',

  USER_LIST: '/user/list',
  USER_CREATE: '/user/create',
  USER_EDIT: '/user/edit',
  USER_DELETE: '/user/delete',
  USER_FETCH_ONE: '/user',

  LOGGER_LIST: '/logger/list',
  LOGGER_SIMPLE_LIST: '/logger/simple-list',
  LOGGER_CREATE: '/logger/create',
  LOGGER_EDIT: '/logger/edit',
  LOGGER_DELETE: '/logger/delete',
  LOGGER_FETCH_ONE: '/logger',

  STORE_LIST: '/store/list',
  STORE_SIMPLE_LIST: '/store/simple-list',
  STORE_CREATE: '/store/create',
  STORE_EDIT: '/store/edit',
  STORE_DELETE: '/store/delete',
  STORE_FETCH_ONE: '/store',

  BRANCH_LIST: '/branch/list',
  BRANCH_SIMPLE_LIST: '/branch/simple-list',
  BRANCH_CREATE: '/branch/create',
  BRANCH_EDIT: '/branch/edit',
  BRANCH_DELETE: '/branch/delete',
  BRANCH_FETCH_ONE: '/branch',

  COMPANY_LIST: '/company/list',
  COMPANY_SIMPLE_LIST: '/company/simple-list',
  COMPANY_CREATE: '/company/create',
  COMPANY_EDIT: '/company/edit',
  COMPANY_DELETE: '/company/delete',
  COMPANY_FETCH_ONE: '/company',
}